DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS TODO;

CREATE TABLE POSTS (
    ID INTEGER  PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    POSTTIME DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TODO (
    ID INTEGER PRIMARY KEY,
    TASK TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    POSTTIME DATE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY,
    USERID TEXT NOT NULL,
    USERPW TEXT NOT NULL
)